import React,{useEffect,useMemo,useRef,useState}from'react'
import{createRoot}from'react-dom/client'
import{Home,ReceiptText,Target,Flame,WalletCards,Plus,Upload,X,ChevronRight,ShoppingBasket,Waves,Dumbbell,HeartHandshake,Wifi,Smartphone,Utensils,Car,Banknote,Pill,Crown,MoreHorizontal,Trash2,Sparkles,Settings2,Gem,PiggyBank,Wallet,Landmark,Pencil,ShieldCheck}from'lucide-react'
import'./styles.css'
const K='finos-state-v2',LEG='finos-state-v1',id=()=>crypto.randomUUID?.()||Math.random().toString(36).slice(2),today=()=>new Date().toISOString().slice(0,10)
const CYCLE_DAY=28,ymd=d=>`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`,parseYmd=s=>{let[a,b,c]=(s||'').split('-').map(Number);return new Date(a,b-1,c)},cycleFor=(d=new Date())=>{let start=d.getDate()>=CYCLE_DAY?new Date(d.getFullYear(),d.getMonth(),CYCLE_DAY):new Date(d.getFullYear(),d.getMonth()-1,CYCLE_DAY),end=new Date(start.getFullYear(),start.getMonth()+1,CYCLE_DAY-1);return{start:ymd(start),end:ymd(end),label:end.toLocaleDateString('en-US',{month:'short',year:'numeric'})}},inCycle=(date,c)=>date>=c.start&&date<=c.end
const money=n=>`${new Intl.NumberFormat('en-EG',{maximumFractionDigits:0}).format(Math.max(0,+n||0))} EGP`,clamp=(n,a,b)=>Math.min(Math.max(n,a),b)
const cats=[['Groceries',2000,'flex','groceries'],['Swimming',1500,'fixed','swimming'],['Gym fund',1333,'fixed','gym'],['Mother',500,'fixed','family'],['Internet',800,'fixed','internet'],['Phone',300,'fixed','phone'],['Uber / Talabat',200,'flex','food'],['Fuel',200,'flex','fuel'],['Pocket money',300,'flex','cash'],['Supplements',100,'flex','supplements'],['Prime & fees',70,'fixed','subscription']].map(([name,budget,kind,icon])=>({id:id(),name,budget,kind,icon}))
const seed={profile:{age:27,salary:30000,retirementAge:65},spendingTarget:7303,categories:cats,transactions:[],goals:[{id:id(),name:'Home renovation',target:350000,funded:72403,priority:1},{id:id(),name:'Honeymoon',target:0,funded:0,priority:2}],assets:[{id:id(),name:'CIB cash',type:'cash',balance:52930,monthly:0,rate:0,earmark:'Cash'},{id:id(),name:'Home Renovation · Klouds',type:'investment',balance:72403,monthly:0,rate:20,earmark:'Home renovation'},{id:id(),name:'BSB Gold Fund',type:'gold',balance:75088,monthly:0,rate:5,earmark:'Honeymoon / future goals'},{id:id(),name:'Retirement',type:'retirement',balance:0,monthly:6500,rate:5,earmark:'Retirement'}],fire:{monthlyLifestyle:25300,withdrawalRate:3.5,realReturn:5}}
function load(){try{let s=localStorage.getItem(K);if(s)return JSON.parse(s);let l=localStorage.getItem(LEG);if(l){l=JSON.parse(l);return{...seed,profile:{...seed.profile,...l.profile},goals:l.goals?.length?l.goals:seed.goals,assets:l.assets?.length?l.assets:seed.assets,fire:{...seed.fire,...l.fire}}}}catch{}return seed}
const icons={groceries:ShoppingBasket,swimming:Waves,gym:Dumbbell,family:HeartHandshake,internet:Wifi,phone:Smartphone,food:Utensils,fuel:Car,cash:Banknote,supplements:Pill,subscription:Crown}
const assetIcon=t=>t==='gold'?Gem:t==='retirement'?PiggyBank:t==='cash'?Wallet:Landmark
function FV(b,m,r,y){let n=Math.max(0,Math.round(y*12)),mr=Math.pow(1+r/100,1/12)-1;if(!n)return+b||0;if(Math.abs(mr)<1e-9)return(+b||0)+(+m||0)*n;return(+b||0)*Math.pow(1+mr,n)+(+m||0)*((Math.pow(1+mr,n)-1)/mr)}
function target(f){return(+f.monthlyLifestyle||0)*12/(+f.withdrawalRate/100)}
function req(t,c,y,r){let n=Math.round(y*12),mr=Math.pow(1+r/100,1/12)-1,g=c*Math.pow(1+mr,n),gap=Math.max(0,t-g);return gap?gap/((Math.pow(1+mr,n)-1)/mr):0}
function Progress({v}){return <div className="progress"><span style={{width:`${clamp(v,0,100)}%`}}/></div>}
function Sheet({title,onClose,children}){return <div className="sheet-backdrop" onMouseDown={e=>e.target===e.currentTarget&&onClose()}><section className="sheet"><header><h3>{title}</h3><button onClick={onClose}><X size={20}/></button></header>{children}</section></div>}
function Nav({tab,setTab}){return <nav className="bottom-nav">{[["today",Home,'Today'],['spending',ReceiptText,'Spending'],['goals',Target,'Goals'],['freedom',Flame,'Freedom'],['money',WalletCards,'Money']].map(([k,I,l])=><button key={k} className={tab===k?'active':''} onClick={()=>setTab(k)}><I size={19}/><span>{l}</span></button>)}</nav>}
function App(){const[data,setData]=useState(load),[tab,setTab]=useState('today'),[sheet,setSheet]=useState(null),fileRef=useRef();useEffect(()=>localStorage.setItem(K,JSON.stringify(data)),[data])
 const cycle=cycleFor(),tx=data.transactions.filter(t=>inCycle(t.date||'',cycle)&&t.type!=='transfer'),spent=tx.reduce((s,t)=>s+(+t.amount||0),0),remaining=Math.max(0,data.spendingTarget-spent),d=new Date(),end=parseYmd(cycle.end),daysLeft=Math.max(1,Math.ceil((end-d)/(86400000))+1),fixedBudget=data.categories.filter(c=>c.kind==='fixed').reduce((s,c)=>s+(+c.budget||0),0),flexBudget=Math.max(0,data.spendingTarget-fixedBudget),flexSpent=tx.filter(t=>data.categories.find(c=>c.id===t.categoryId)?.kind!=='fixed').reduce((s,t)=>s+(+t.amount||0),0),flexRemaining=Math.max(0,flexBudget-flexSpent),safe=flexRemaining/daysLeft
 const by=Object.fromEntries(data.categories.map(c=>[c.id,tx.filter(t=>t.categoryId===c.id).reduce((s,t)=>s+(+t.amount||0),0)])),ret=data.assets.filter(a=>a.type==='retirement'),rb=ret.reduce((s,a)=>s+(+a.balance||0),0),rm=ret.reduce((s,a)=>s+(+a.monthly||0),0),ft=target(data.fire),years=data.profile.retirementAge-data.profile.age,need=req(ft,rb,years,data.fire.realReturn),total=data.assets.reduce((s,a)=>s+(+a.balance||0),0)
 const freedomAge=useMemo(()=>{for(let a=data.profile.age;a<=80;a++)if(FV(rb,rm,data.fire.realReturn,a-data.profile.age)>=ft)return a;return null},[rb,rm,data.fire,data.profile])
 const goal=[...data.goals].sort((a,b)=>(a.priority||9)-(b.priority||9)).find(g=>+g.target>+g.funded),left=Math.max(0,data.profile.salary-data.spendingTarget-Math.max(6500,rm))
 function addExpense(x){setData(d=>({...d,transactions:[{id:id(),type:'expense',date:today(),...x,amount:+x.amount},...d.transactions]}));setSheet(null)}
 async function importCsv(file){
  const text=await file.text(),lines=text.split(/\r?\n/).filter(Boolean);let rows=[];
  const findCat=name=>data.categories.find(c=>c.name===name)?.id||'';
  const parseDate=x=>{let d=new Date(x);return Number.isNaN(d.getTime())?today():ymd(d)};
  const split=line=>{let out=[],cur='',q=false;for(let ch of line){if(ch==='"')q=!q;else if(ch===','&&!q){out.push(cur);cur=''}else cur+=ch}out.push(cur);return out};
  for(let line of lines){let p=split(line);if(!p[0]||/^date$/i.test(p[0])||/transaction list/i.test(p[0]))continue;let desc=(p[1]||'').trim(),upper=desc.toUpperCase(),raw=(p[2]||'').replace(/EGP/ig,'').replace(/,/g,'').trim(),signed=parseFloat(raw);if(!Number.isFinite(signed)||signed>=0)continue;let amount=Math.abs(signed),type='expense',categoryId='';
    if(/THUNDR|THNDR|DIRECT DEBIT|C\.C AC NO/.test(upper)){type='transfer'}
    else if(/CHILL.?OUT/.test(upper))categoryId=findCat('Fuel');
    else if(/MUSCLE TEMPLE/.test(upper))categoryId=findCat('Gym fund');
    else if(/MAX MUSCLE/.test(upper))categoryId=findCat('Supplements');
    else if(/WE FBB/.test(upper))categoryId=findCat('Internet');
    else if(/MOBILE RECHARGE/.test(upper))categoryId=findCat('Phone');
    else if(/MY TELDA/.test(upper))categoryId=findCat('Uber / Talabat');
    else if(/ATM ID|NBE ATM|BDC NASR|NBK EGYPT/.test(upper))categoryId=findCat('Pocket money');
    else if(/ISLAM ASHRAF/.test(upper))categoryId=findCat('Swimming');
    else if(/DOHA MADNY/.test(upper))categoryId=findCat('Mother');
    else if(/FLAMINGO|FLAMNGO|GOMLA|CARREFOUR|SEOUDI|BEIT ELGOMLA/.test(upper))categoryId=findCat('Groceries');
    else if(/AMAZON|PRIME/.test(upper))categoryId=findCat('Prime & fees');
    rows.push({id:id(),type,date:parseDate(p[0]),amount,categoryId,note:desc.slice(0,110)});
  }
  setData(d=>({...d,transactions:[...rows,...d.transactions]}));setSheet({type:'imported',count:rows.length})
 }
 return <div className="app-shell"><header className="topbar"><div><b>FinOS</b><small>Money without the mental load.</small></div><button className="avatar" onClick={()=>setSheet({type:'settings'})}>ZT</button></header><main className="content">
 {tab==='today'&&<><section className="hero"><div><small>SAFE TO SPEND TODAY · FLEXIBLE MONEY</small><h1>{money(safe)}</h1><p className="hero-note">{cycle.label} cycle · {cycle.start.slice(5).replace('-','/')}–{cycle.end.slice(5).replace('-','/')} · fixed commitments already reserved</p></div><em>{spent>data.spendingTarget?'Over budget':'On track'}</em><Progress v={spent/data.spendingTarget*100}/><footer><span>{money(spent)} logged this cycle</span><span>{money(flexRemaining)} flexible left</span></footer></section><div className="quick"><button className="accent" onClick={()=>setSheet({type:'expense'})}><Plus/> <span><b>Add expense</b><small>10 seconds</small></span></button><button onClick={()=>setSheet({type:'payday'})}><Sparkles/> <span><b>Payday</b><small>Allocate salary</small></span></button></div><Section title="Where your money is going" action={()=>setTab('spending')}>{data.categories.slice(0,5).map(c=>{let I=icons[c.icon]||MoreHorizontal,u=by[c.id]||0;return <button className="budget-row" key={c.id} onClick={()=>setTab('spending')}><i><I size={18}/></i><div><span><b>{c.name}</b><small>{money(u)} / {money(c.budget)}</small></span><Progress v={u/c.budget*100}/></div><strong>{money(Math.max(0,c.budget-u))}</strong></button>})}</Section><Section title="Next paycheck plan"><div className="paycheck"><div className="plan-note">Planning only — nothing has moved yet.</div><p><span>Salary</span><b>{money(data.profile.salary)}</b></p><p><span>Keep for {cycle.label} living</span><b>− {money(data.spendingTarget)}</b></p><p><span>Retirement</span><b>− {money(Math.max(6500,rm))}</b></p><p className="goal"><span>{goal?.name||'Next goal'}</span><b>{money(left)}</b></p><button className="full" onClick={()=>setSheet({type:'payday'})}>Review allocation</button></div></Section></>}
 {tab==='spending'&&<><Intro kicker="SPENDING" title={`${cycle.label}: stay under ${money(data.spendingTarget)}.`} text={`Your FinOS month runs ${cycle.start.slice(5).replace('-','/')} → ${cycle.end.slice(5).replace('-','/')}. Transfers and investments never count as lifestyle spending.`} add={()=>setSheet({type:'expense'})}/><div className="stats"><Stat l="Spent" v={money(spent)}/><Stat l="Remaining" v={money(remaining)}/><Stat l="Flexible / day" v={money(safe)}/></div><Section title="Category limits" extra={<button className="text-btn" onClick={()=>setSheet({type:'budgets'})}><Settings2 size={16}/>Edit</button>}><div className="cat-grid">{data.categories.map(c=>{let I=icons[c.icon]||MoreHorizontal,u=by[c.id]||0;return <article className="cat" key={c.id}><div><i><I size={17}/></i><small>{c.kind}</small></div><b>{c.name}</b><span>{money(u)} / {money(c.budget)}</span><Progress v={u/c.budget*100}/></article>})}</div></Section><Section title="Transactions" extra={<><button className="text-btn" onClick={()=>fileRef.current?.click()}><Upload size={16}/>Import CSV</button><input ref={fileRef} hidden type="file" accept=".csv" onChange={e=>e.target.files?.[0]&&importCsv(e.target.files[0])}/></>}>{data.transactions.length?data.transactions.slice(0,50).map(t=>{let c=data.categories.find(c=>c.id===t.categoryId),I=icons[c?.icon]||MoreHorizontal;return <div className="tx" key={t.id}><i><I size={17}/></i><div><b>{c?.name||(t.type==='transfer'?'Transfer / investment':'Needs category')}</b><small>{t.note||'Expense'} · {t.date}</small></div><strong>{t.type==='transfer'?'Excluded':'− '+money(t.amount)}</strong><button onClick={()=>setData(d=>({...d,transactions:d.transactions.filter(x=>x.id!==t.id)}))}><Trash2 size={15}/></button></div>}):<div className="empty">No expenses yet. Add one or import a CIB CSV.</div>}</Section></>}
 {tab==='goals'&&<><Intro kicker="GOALS" title="Fund what matters next." text="One priority at a time keeps your money focused." add={()=>setSheet({type:'goal'})}/><div className="goals">{data.goals.map((g,i)=><article key={g.id}><span>#{i+1}</span><div><header><div><h2>{g.name}</h2><small>{g.target?`${money(Math.max(0,g.target-g.funded))} remaining`:'Set a target'}</small></div><button onClick={()=>setSheet({type:'goal',goal:g})}><Pencil size={16}/></button></header><Progress v={g.target?g.funded/g.target*100:0}/><footer><b>{money(g.funded)}</b><span>of {money(g.target)}</span></footer></div></article>)}</div></>}
 {tab==='freedom'&&<><Intro kicker="FREEDOM" title="Retirement, without the spreadsheet." text="Planning values use today’s purchasing power."/><section className="freedom"><div><small>PROJECTED FREEDOM AGE</small><h1>{freedomAge||'80+'}</h1><p>At {money(rm)}/month and {data.fire.realReturn}% real return.</p></div><Flame size={45}/></section><div className="metrics"><Stat l="FIRE target" v={money(ft)}/><Stat l="Retirement balance" v={money(rb)}/><Stat l={`Needed for age ${data.profile.retirementAge}`} v={money(need)}/><Stat l="Your contribution" v={money(rm)}/></div><Section title="Adjust the plan"><div className="sliders"><label>Retirement age <b>{data.profile.retirementAge}</b><input type="range" min="45" max="70" value={data.profile.retirementAge} onChange={e=>setData(d=>({...d,profile:{...d.profile,retirementAge:+e.target.value}}))}/></label><label>Real return <b>{data.fire.realReturn}%</b><input type="range" min="2" max="7" step=".5" value={data.fire.realReturn} onChange={e=>setData(d=>({...d,fire:{...d.fire,realReturn:+e.target.value}}))}/></label></div></Section></>}
 {tab==='money'&&<><Intro kicker="MONEY" title={money(total)} text="Everything you own, with a job attached to it." add={()=>setSheet({type:'asset'})}/><div className="assets">{data.assets.map(a=>{let I=assetIcon(a.type);return <article key={a.id}><i><I size={20}/></i><div><b>{a.name}</b><small>{a.earmark||'Unassigned'}</small></div><strong>{money(a.balance)}<small>{a.monthly?`+${money(a.monthly)}/mo`:a.type==='cash'?'Cash':`${a.rate}% assumed`}</small></strong></article>})}</div><div className="insight"><ShieldCheck/><div><b>Goal money stays separate from retirement.</b><p>FinOS uses earmarks so renovation money never accidentally boosts your FIRE progress.</p></div></div></>}
 </main><Nav tab={tab} setTab={setTab}/>{sheet&&renderSheet(sheet,{data,setData,setSheet,addExpense,left,rm,goal})}</div>}
function Section({title,action,extra,children}){return <section className="section"><header><h2>{title}</h2>{extra||action&&<button className="text-btn" onClick={action}>See all <ChevronRight size={16}/></button>}</header>{children}</section>}
function Intro({kicker,title,text,add}){return <div className="intro"><div><small>{kicker}</small><h1>{title}</h1><p>{text}</p></div>{add&&<button className="round" onClick={add}><Plus/></button>}</div>}
function Stat({l,v}){return <div className="stat"><small>{l}</small><b>{v}</b></div>}
function renderSheet(s,{data,setData,setSheet,addExpense,left,rm,goal}){let close=()=>setSheet(null);if(s.type==='expense')return <Expense data={data} close={close} add={addExpense}/>;if(s.type==='payday')return <Sheet title="Payday" onClose={close}><div className="payday-sheet"><div><small>PAYCHECK</small><b>{money(data.profile.salary)}</b></div><p><span>Keep for living</span><b>{money(data.spendingTarget)}</b></p><p><span>Retirement</span><b>{money(Math.max(6500,rm))}</b></p><p className="result"><span>Available for {goal?.name||'next goal'}</span><b>{money(left)}</b></p><small>Nothing moves until you confirm it outside FinOS. This is your recommended allocation only.</small><button className="full" onClick={close}>Done</button></div></Sheet>;if(s.type==='budgets')return <Sheet title="Monthly budget" onClose={close}><div className="form"><label>Total target<input type="number" value={data.spendingTarget} onChange={e=>setData(d=>({...d,spendingTarget:+e.target.value}))}/></label>{data.categories.map(c=><label key={c.id}>{c.name}<input type="number" value={c.budget} onChange={e=>setData(d=>({...d,categories:d.categories.map(x=>x.id===c.id?{...x,budget:+e.target.value}:x)}))}/></label>)}<button className="full" onClick={close}>Save</button></div></Sheet>;if(s.type==='goal')return <Goal goal={s.goal} close={close} save={g=>{setData(d=>({...d,goals:s.goal?d.goals.map(x=>x.id===g.id?g:x):[...d.goals,g]}));close()}}/>;if(s.type==='asset')return <Asset close={close} save={a=>{setData(d=>({...d,assets:[...d.assets,a]}));close()}}/>;if(s.type==='imported')return <Sheet title="CSV imported" onClose={close}><div className="empty">Imported {s.count} debit rows with their original transaction dates. FinOS automatically places each one into the correct 28th→27th cycle. Review anything marked “Needs category”.</div><button className="full" onClick={close}>Review</button></Sheet>;if(s.type==='settings')return <Sheet title="FinOS settings" onClose={close}><div className="form"><label>Salary<input type="number" value={data.profile.salary} onChange={e=>setData(d=>({...d,profile:{...d.profile,salary:+e.target.value}}))}/></label><label>Age<input type="number" value={data.profile.age} onChange={e=>setData(d=>({...d,profile:{...d.profile,age:+e.target.value}}))}/></label><small>Your data is stored only in this browser for now.</small><button className="full" onClick={close}>Done</button></div></Sheet>}
function Expense({data,close,add}){const[a,setA]=useState(''),[c,setC]=useState(data.categories[0]?.id||''),[n,setN]=useState('');return <Sheet title="Add expense" onClose={close}><form className="form" onSubmit={e=>{e.preventDefault();if(+a>0)add({amount:+a,categoryId:c,note:n})}}><label>Amount<input autoFocus type="number" step=".01" value={a} onChange={e=>setA(e.target.value)} placeholder="0 EGP"/></label><label>Category<select value={c} onChange={e=>setC(e.target.value)}>{data.categories.map(x=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label><label>Note<input value={n} onChange={e=>setN(e.target.value)} placeholder="e.g. Metro Market"/></label><button className="full">Add expense</button></form></Sheet>}
function Goal({goal,close,save}){const[n,setN]=useState(goal?.name||''),[t,setT]=useState(goal?.target||''),[f,setF]=useState(goal?.funded||'');return <Sheet title={goal?'Edit goal':'New goal'} onClose={close}><form className="form" onSubmit={e=>{e.preventDefault();save({id:goal?.id||id(),name:n||'Goal',target:+t||0,funded:+f||0,priority:goal?.priority||9})}}><label>Name<input value={n} onChange={e=>setN(e.target.value)}/></label><label>Target<input type="number" value={t} onChange={e=>setT(e.target.value)}/></label><label>Funded<input type="number" value={f} onChange={e=>setF(e.target.value)}/></label><button className="full">Save goal</button></form></Sheet>}
function Asset({close,save}){const[n,setN]=useState(''),[t,setT]=useState('investment'),[b,setB]=useState(''),[m,setM]=useState(''),[r,setR]=useState('5'),[e,setE]=useState('');return <Sheet title="Add account / asset" onClose={close}><form className="form" onSubmit={x=>{x.preventDefault();save({id:id(),name:n||'Asset',type:t,balance:+b||0,monthly:+m||0,rate:+r||0,earmark:e})}}><label>Name<input value={n} onChange={x=>setN(x.target.value)}/></label><label>Type<select value={t} onChange={x=>setT(x.target.value)}><option value="cash">Cash</option><option value="investment">Investment</option><option value="gold">Gold</option><option value="retirement">Retirement</option></select></label><label>Balance<input type="number" value={b} onChange={x=>setB(x.target.value)}/></label><label>Monthly contribution<input type="number" value={m} onChange={x=>setM(x.target.value)}/></label><label>Annual growth assumption<input type="number" value={r} onChange={x=>setR(x.target.value)}/></label><label>Earmark<input value={e} onChange={x=>setE(x.target.value)}/></label><button className="full">Add asset</button></form></Sheet>}
createRoot(document.getElementById('root')).render(<App/>)
