import React,{useEffect,useMemo,useReducer,useRef,useState} from 'react'
import {createRoot} from 'react-dom/client'
import {
  Home,ReceiptText,Target,Flame,WalletCards,Plus,Upload,X,ShoppingBasket,Waves,Dumbbell,HeartHandshake,Wifi,Smartphone,Utensils,Car,Banknote,Pill,Crown,MoreHorizontal,Sparkles,Settings2,Gem,PiggyBank,Wallet,Landmark,ShieldCheck,Bus,ParkingCircle,Stethoscope,Shirt,Gamepad2,GraduationCap,Gift,Plane,House,HeartPulse,MonitorSmartphone,BadgeDollarSign,HandCoins,Coffee,Package,CheckCircle2,AlertTriangle,CalendarDays,CreditCard,ArrowRightLeft,ChevronLeft,ChevronRight,TrendingUp,TrendingDown,Check,SlidersHorizontal,Flag,History,RotateCcw
} from 'lucide-react'
import './styles.css'
import {
  uid,todayYmd,cycleFor,cycleFromStart,shiftCycle,inCycle,money,clamp,categoryIdByName,accountValue,assetsTotal,liabilitiesTotal,netWorth,liquidTotal,budgetTotal,cycleExpenses,cycleSpent,categorySpend,goalFunded,retirementAccount,operatingAccount,currentPriorityGoal,fireTarget,futureValue,requiredMonthly,financialHealth
} from './domain/model.js'
import {loadState,saveState,reducer} from './store/financeStore.js'

const icons={groceries:ShoppingBasket,eating:Utensils,delivery:Package,uber:Car,transport:Bus,fuel:Car,parking:ParkingCircle,car:Car,swimming:Waves,gym:Dumbbell,supplements:Pill,sportsgear:Dumbbell,family:HeartHandshake,gift:Gift,charity:HandCoins,internet:Wifi,phone:Smartphone,subscription:Crown,fees:BadgeDollarSign,health:HeartPulse,doctor:Stethoscope,care:Sparkles,clothes:Shirt,electronics:MonitorSmartphone,home:House,entertainment:Sparkles,gaming:Gamepad2,travel:Plane,cash:Banknote,education:GraduationCap,government:Landmark,coffee:Coffee,shopping:ShoppingBasket,misc:MoreHorizontal,review:AlertTriangle}
const accountIcon=t=>t==='physical_gold'||t==='gold_fund'?Gem:t==='retirement'?PiggyBank:t==='cash'?Wallet:Landmark

function App(){
  const [state,dispatch]=useReducer(reducer,undefined,loadState)
  const [tab,setTab]=useState('today')
  const [modal,setModal]=useState(null)
  const [viewCycleStart,setViewCycleStart]=useState(cycleFor(new Date(),state.settings.cycleDay).start)
  const fileRef=useRef(null)
  useEffect(()=>saveState(state),[state])

  const metrics=useMemo(()=>deriveMetrics(state),[state])
  const ctx={state,dispatch,metrics,setModal,viewCycleStart,setViewCycleStart,fileRef}

  return <div className="app-shell">
    <Header state={state} metrics={metrics} setModal={setModal}/>
    <main className="content">
      {tab==='today'&&<Today {...ctx}/>} 
      {tab==='spending'&&<Spending {...ctx}/>} 
      {tab==='goals'&&<Goals {...ctx}/>} 
      {tab==='freedom'&&<Freedom {...ctx}/>} 
      {tab==='money'&&<Money {...ctx}/>} 
    </main>
    <Nav tab={tab} setTab={setTab}/>
    <input ref={fileRef} type="file" accept=".csv,text/csv" hidden onChange={e=>handleCsv(e,state,dispatch,setModal)}/>
    {modal&&<ModalRouter modal={modal} close={()=>setModal(null)} {...ctx}/>} 
  </div>
}

function deriveMetrics(state){
  const health=financialHealth(state)
  const cycle=health.cycle
  const currentTx=cycleExpenses(state,cycle)
  const categoryMap=Object.fromEntries(state.categories.map(c=>[c.id,categorySpend(state,c.id,cycle)]))
  const fixedBudget=state.categories.filter(c=>c.active!==false&&c.kind==='fixed'&&c.name!=='Needs review').reduce((s,c)=>s+(+c.budget||0),0)
  const flexBudget=Math.max(0,state.settings.monthlySpendingTarget-fixedBudget)
  const flexSpent=currentTx.filter(t=>state.categories.find(c=>c.id===t.categoryId)?.kind!=='fixed').reduce((s,t)=>s+(+t.amount||0),0)
  const daysLeft=Math.max(1,Math.ceil((new Date(cycle.end+'T23:59:59')-new Date())/86400000))
  const flexRemaining=Math.max(0,flexBudget-flexSpent)
  const primaryGoal=currentPriorityGoal(state)
  const retirement=retirementAccount(state)
  const plannedGoal=Math.max(0,state.profile.salary-state.settings.monthlySpendingTarget-(+retirement?.monthlyContribution||0))
  const nw=netWorth(state)
  const firstMillion=state.milestones.find(m=>/1m/i.test(m.name)||m.target===1000000)
  return {health,cycle,currentTx,categoryMap,fixedBudget,flexBudget,flexSpent,flexRemaining,safeToday:flexRemaining/daysLeft,daysLeft,primaryGoal,retirement,plannedGoal,nw,firstMillion}
}

function Header({state,metrics,setModal}){return <header className="topbar"><div><div className="brand"><span className="brand-mark">F</span><b>FinOS</b></div><p>{metrics.cycle.label} · {metrics.cycle.start} → {metrics.cycle.end}</p></div><button className="icon-button" onClick={()=>setModal({type:'settings'})} aria-label="Settings"><Settings2 size={19}/></button></header>}
function Nav({tab,setTab}){const items=[['today',Home,'Today'],['spending',ReceiptText,'Spending'],['goals',Target,'Goals'],['freedom',Flame,'Freedom'],['money',WalletCards,'Money']];return <nav className="bottom-nav">{items.map(([key,Icon,label])=><button key={key} className={tab===key?'active':''} onClick={()=>setTab(key)}><Icon size={19}/><span>{label}</span></button>)}</nav>}

function Today({state,dispatch,metrics,setModal}){
  const budgetGap=budgetTotal(state)-state.settings.monthlySpendingTarget
  const attention=[]
  if(!metrics.health.cardPaid) attention.push({icon:CreditCard,title:'Credit card not cleared',text:`${money(metrics.health.cardDue)} outstanding this cycle.`,action:()=>setModal({type:'payCard'})})
  if(!metrics.health.retirementFunded) attention.push({icon:PiggyBank,title:'Retirement not funded yet',text:`Your ${money(metrics.retirement?.monthlyContribution||0)} payday rule is still pending.`,action:()=>setModal({type:'transfer',toId:metrics.retirement?.id})})
  if(Math.abs(budgetGap)>0.01) attention.push({icon:AlertTriangle,title:'Budget needs balancing',text:`Category allocations are ${budgetGap>0?money(budgetGap)+' over':money(Math.abs(budgetGap))+' under'} your monthly target.`,action:()=>setModal({type:'budget'})})
  return <section className="page animate-page">
    <div className="hero-card">
      <div className="eyebrow">Safe flexible spend today</div>
      <div className="hero-value">{money(metrics.safeToday)}</div>
      <div className="hero-sub">{money(metrics.flexRemaining)} flexible money left · {metrics.daysLeft} day{metrics.daysLeft!==1?'s':''} remaining</div>
      <Progress value={metrics.flexBudget?metrics.flexSpent/metrics.flexBudget*100:0}/>
      <div className="hero-footer"><span>{money(metrics.health.spent)} spent this cycle</span><span>{money(metrics.health.remaining)} vs target</span></div>
    </div>

    <div className="quick-grid">
      <button className="quick primary" onClick={()=>setModal({type:'expense'})}><Plus/><span><b>Add expense</b><small>Updates budget + account/card</small></span></button>
      <button className="quick" onClick={()=>setModal({type:'afford'})}><ShieldCheck/><span><b>Can I afford it?</b><small>Checks the exact category</small></span></button>
      <button className="quick" onClick={()=>setModal({type:'payday'})}><CalendarDays/><span><b>Payday plan</b><small>Retirement first, then goals</small></span></button>
      <button className="quick" onClick={()=>setModal({type:'transfer'})}><ArrowRightLeft/><span><b>Move money</b><small>Accounts stay synchronized</small></span></button>
    </div>

    {attention.length>0&&<section><SectionTitle title="Needs attention"/><div className="attention-list">{attention.map((a,i)=><button key={i} className="attention-card" onClick={a.action}><a.icon size={19}/><span><b>{a.title}</b><small>{a.text}</small></span><ChevronRight size={18}/></button>)}</div></section>}

    <section><SectionTitle title="This cycle" action="Edit budget" onAction={()=>setModal({type:'budget'})}/><div className="summary-grid">
      <MetricCard label="Monthly target" value={money(state.settings.monthlySpendingTarget)} note={`${money(metrics.health.spent)} used`}/>
      <MetricCard label="Liquid money" value={money(metrics.health.liquid)} note={`${money(state.settings.liquidReserve)} floor`}/>
      <MetricCard label="Net worth" value={money(metrics.nw)} note="Assets − card debt" trend={snapshotTrend(state)}/>
    </div></section>

    <section><SectionTitle title="Category pulse" action="See all" onAction={()=>setModal({type:'budget'})}/><div className="category-pulse">{state.categories.filter(c=>c.active!==false&&c.name!=='Needs review'&&c.budget>0).slice(0,8).map(c=>{
      const used=metrics.categoryMap[c.id]||0, left=(+c.budget||0)-used, Icon=icons[c.icon]||MoreHorizontal
      return <article key={c.id}><div className="category-icon"><Icon size={17}/></div><div><b>{c.name}</b><small>{money(Math.max(0,left))} left of {money(c.budget)}</small><Progress value={c.budget?used/c.budget*100:0}/></div></article>
    })}</div></section>

    <section><SectionTitle title="Your priorities"/><div className="priority-list">
      {state.goals.sort((a,b)=>a.priority-b.priority).map(g=><GoalRow key={g.id} state={state} goal={g}/>) }
      {metrics.firstMillion&&<div className="priority-row"><span className="priority-number">{metrics.firstMillion.priority}</span><div><b>{metrics.firstMillion.name}</b><small>{money(metrics.nw)} / {money(metrics.firstMillion.target)}</small><Progress value={metrics.nw/metrics.firstMillion.target*100}/></div><strong>{Math.round(clamp(metrics.nw/metrics.firstMillion.target*100,0,100))}%</strong></div>}
    </div></section>
  </section>
}

function Spending({state,dispatch,metrics,setModal,viewCycleStart,setViewCycleStart,fileRef}){
  const view=cycleFromStart(viewCycleStart,state.settings.cycleDay), tx=cycleExpenses(state,view), spent=cycleSpent(state,view), isCurrent=view.start===metrics.cycle.start
  const closed=state.cycleClosures.find(c=>c.cycleStart===view.start)
  const byCat=state.categories.map(c=>({...c,spent:categorySpend(state,c.id,view)})).filter(c=>c.spent>0||c.budget>0)
  return <section className="page animate-page">
    <div className="cycle-switcher"><button onClick={()=>setViewCycleStart(shiftCycle(viewCycleStart,-1))}><ChevronLeft/></button><div><b>{view.label}</b><small>{view.start} → {view.end}{closed?' · Closed':''}</small></div><button disabled={isCurrent} onClick={()=>setViewCycleStart(shiftCycle(viewCycleStart,1))}><ChevronRight/></button></div>
    <div className="summary-grid two"><MetricCard label="Spent" value={money(spent)} note={`${money(state.settings.monthlySpendingTarget)} target`}/><MetricCard label="Result" value={money(Math.abs(state.settings.monthlySpendingTarget-spent))} note={spent<=state.settings.monthlySpendingTarget?'under budget':'over budget'} tone={spent<=state.settings.monthlySpendingTarget?'good':'bad'}/></div>
    <div className="action-row"><button className="secondary" onClick={()=>fileRef.current?.click()}><Upload size={17}/>Import CSV</button><button className="secondary" onClick={()=>setModal({type:'expense'})}><Plus size={17}/>Add expense</button>{isCurrent&&!closed&&<button className="secondary" onClick={()=>setModal({type:'closeCycle'})}><Check size={17}/>Close cycle</button>}</div>

    <section><SectionTitle title="Categories" action="Manage budget" onAction={()=>setModal({type:'budget'})}/><div className="spend-categories">{byCat.map(c=>{const Icon=icons[c.icon]||MoreHorizontal;return <article key={c.id}><Icon size={17}/><div><b>{c.name}</b><Progress value={c.budget?c.spent/c.budget*100:c.spent?100:0}/><small>{money(c.spent)} spent · {money(Math.max(0,c.budget-c.spent))} left</small></div><strong>{money(c.budget)}</strong></article>})}</div></section>

    <section><SectionTitle title="Transactions"/><div className="transactions">{tx.length?tx.sort((a,b)=>b.date.localeCompare(a.date)).map(t=><Transaction key={t.id} t={t} state={state} dispatch={dispatch}/>):<Empty text="No expenses in this financial month yet."/>}</div></section>

    <section><SectionTitle title="6-cycle spending"/><HistoryBars state={state} currentStart={viewCycleStart}/></section>
  </section>
}

function Goals({state,dispatch,metrics,setModal}){return <section className="page animate-page">
  <div className="page-heading"><div><div className="eyebrow">Priority system</div><h1>Goals</h1><p>Goal progress is derived from linked accounts — never typed twice.</p></div><button className="icon-button" onClick={()=>setModal({type:'goal'})}><Plus/></button></div>
  <div className="goal-stack">{[...state.goals].sort((a,b)=>a.priority-b.priority).map(g=>{const funded=goalFunded(state,g.id), linked=state.accounts.filter(a=>a.goalId===g.id);return <article className="goal-card" key={g.id}><header><span>Priority {g.priority}</span><button onClick={()=>setModal({type:'goal',goal:g})}>Edit</button></header><h3>{g.name}</h3><div className="goal-money"><b>{money(funded)}</b><span>of {money(g.target)}</span></div><Progress value={g.target?funded/g.target*100:0}/><div className="goal-meta"><span>{money(Math.max(0,g.target-funded))} to go</span><span>{g.targetDate||'No fixed date'}</span></div><div className="linked-row"><small>Linked money</small>{linked.length?linked.map(a=><span key={a.id}>{a.name} · {money(accountValue(a))}</span>):<span>No account linked yet</span>}</div><div className="goal-actions"><button onClick={()=>setModal({type:'transfer',toId:linked[0]?.id})}><ArrowRightLeft size={16}/>Fund goal</button><button onClick={()=>setModal({type:'account',prefillGoalId:g.id})}><Plus size={16}/>Add bucket</button></div></article>})}</div>
  <section><SectionTitle title="First 1M"/><div className="milestone-card"><Flag/><div><b>{money(metrics.nw)}</b><small>Current net worth</small><Progress value={metrics.nw/1000000*100}/><p>{money(Math.max(0,1000000-metrics.nw))} remaining to your first million.</p></div></div></section>
</section>}

function Freedom({state,dispatch,metrics,setModal}){
  const ret=metrics.retirement, balance=ret?accountValue(ret):0, target=fireTarget(state.fire), years=Math.max(0,state.profile.retirementAge-state.profile.age), projected=futureValue(balance,ret?.monthlyContribution||0,state.fire.realReturn,years), needed=requiredMonthly(target,balance,years,state.fire.realReturn)
  return <section className="page animate-page"><div className="page-heading"><div><div className="eyebrow">Long-term independence</div><h1>Freedom</h1><p>Kept separate from renovation and marriage money.</p></div></div>
    <div className="freedom-hero"><Flame/><div><small>FIRE target in today's money</small><b>{money(target)}</b><span>{money(state.fire.monthlyLifestyle)}/month lifestyle · {state.fire.withdrawalRate}% withdrawal rate</span></div></div>
    <div className="summary-grid"><MetricCard label="Retirement balance" value={money(balance)} note={ret?.name||'No retirement account'}/><MetricCard label="Monthly contribution" value={money(ret?.monthlyContribution||0)} note="Protected payday rule"/><MetricCard label={`Projected at ${state.profile.retirementAge}`} value={money(projected)} note={`${state.fire.realReturn}% real return assumption`} tone={projected>=target?'good':'neutral'}/></div>
    <section><SectionTitle title="Plan quality"/><div className="insight-card"><ShieldCheck/><div><b>{(ret?.monthlyContribution||0)>=needed?'On track for the age-65 floor':'Contribution needs attention'}</b><p>At these assumptions, the mathematical contribution needed is about {money(needed)}/month. Your configured contribution is {money(ret?.monthlyContribution||0)}.</p></div></div></section>
    <section><SectionTitle title="Assumptions" action="Edit" onAction={()=>setModal({type:'settings'})}/><div className="rules-grid"><Rule text="Retirement money is never used for goals."/><Rule text="5% real return is used for long-horizon planning, not the current nominal Klouds rate."/><Rule text="Age 65 is a safety deadline; salary growth can move independence earlier."/></div></section>
  </section>
}

function Money({state,dispatch,metrics,setModal}){
  const trend=snapshotTrend(state)
  return <section className="page animate-page"><div className="page-heading"><div><div className="eyebrow">Single source of truth</div><h1>Money</h1><p>Balances here drive net worth, goals, liquidity and affordability everywhere else.</p></div><button className="icon-button" onClick={()=>setModal({type:'account'})}><Plus/></button></div>
    <div className="networth-card"><div><small>Net worth</small><b>{money(metrics.nw)}</b><span>{money(assetsTotal(state))} assets − {money(liabilitiesTotal(state))} liabilities</span></div>{trend&&<div className={`trend-pill ${trend.value>=0?'up':'down'}`}>{trend.value>=0?<TrendingUp size={15}/>:<TrendingDown size={15}/>} {trend.value>=0?'+':''}{money(trend.value)}</div>}</div>
    <div className="summary-grid two"><MetricCard label="Liquid" value={money(liquidTotal(state))} note={`${money(state.settings.liquidReserve)} minimum`}/><MetricCard label="Invested / goal money" value={money(assetsTotal(state)-liquidTotal(state))} note="Includes valued physical gold"/></div>
    <section><SectionTitle title="Accounts & assets"/><div className="account-list">{state.accounts.map(a=><AccountRow key={a.id} account={a} state={state} setModal={setModal}/>)}</div></section>
    <section><SectionTitle title="Credit cards"/><div className="card-list">{state.cards.map(c=><CreditCardRow key={c.id} card={c} state={state} metrics={metrics} setModal={setModal} dispatch={dispatch}/>)}</div></section>
    <section><SectionTitle title="Wealth history" action="Save snapshot" onAction={()=>dispatch({type:'SAVE_SNAPSHOT'})}/><WealthChart state={state}/></section>
  </section>
}

function SectionTitle({title,action,onAction}){return <div className="section-title"><h2>{title}</h2>{action&&<button onClick={onAction}>{action}<ChevronRight size={15}/></button>}</div>}
function Progress({value}){return <div className="progress"><span style={{width:`${clamp(value,0,100)}%`}}/></div>}
function MetricCard({label,value,note,tone='neutral',trend}){return <article className={`metric-card ${tone}`}><small>{label}</small><b>{value}</b><span>{trend?`${trend.value>=0?'+':''}${money(trend.value)} since last snapshot`:note}</span></article>}
function Empty({text}){return <div className="empty"><Sparkles size={18}/><span>{text}</span></div>}
function Rule({text}){return <div className="rule"><CheckCircle2 size={17}/><span>{text}</span></div>}
function GoalRow({state,goal}){const funded=goalFunded(state,goal.id);return <div className="priority-row"><span className="priority-number">{goal.priority}</span><div><b>{goal.name}</b><small>{money(funded)} / {money(goal.target)}</small><Progress value={goal.target?funded/goal.target*100:0}/></div><strong>{Math.round(clamp(funded/goal.target*100,0,100))}%</strong></div>}
function Transaction({t,state,dispatch}){const c=state.categories.find(x=>x.id===t.categoryId), Icon=icons[c?.icon]||ReceiptText;const source=t.cardId?state.cards.find(x=>x.id===t.cardId)?.name:state.accounts.find(x=>x.id===t.accountId)?.name;return <article className="transaction"><div className="category-icon"><Icon size={16}/></div><div><b>{t.note||t.merchant||c?.name||'Expense'}</b><small>{t.date} · {c?.name||'Needs review'}{source?` · ${source}`:''}</small></div><strong>-{money(t.amount)}</strong><button className="ghost-delete" onClick={()=>dispatch({type:'DELETE_TRANSACTION',id:t.id})}>×</button></article>}
function AccountRow({account,state,setModal}){const Icon=accountIcon(account.type), goal=state.goals.find(g=>g.id===account.goalId);return <article className="account-row" onClick={()=>setModal({type:'account',account})}><div className="account-icon"><Icon size={18}/></div><div><b>{account.name}</b><small>{goal?`Linked to ${goal.name}`:account.note||account.type.replaceAll('_',' ')}</small></div><strong>{money(accountValue(account))}</strong><ChevronRight size={17}/></article>}
function CreditCardRow({card,state,metrics,setModal,dispatch}){const cycle=metrics.cycle, payment=state.cardPayments.find(p=>p.cardId===card.id&&p.cycleStart===cycle.start), paid=payment?.status==='paid'||card.balance<=0;return <article className={`credit-row ${paid?'paid':''}`}><div><CreditCard/><span><b>{card.name}</b><small>Due day {card.dueDay} · {paid?'Paid this cycle':'Needs full payment'}</small></span></div><strong>{money(card.balance)}</strong><div className="card-actions">{!paid&&<button onClick={()=>setModal({type:'payCard',card})}>Pay in full</button>}<button className="subtle" onClick={()=>setModal({type:'card',card})}>Edit</button></div></article>}

function HistoryBars({state,currentStart}){const starts=Array.from({length:6},(_,i)=>shiftCycle(currentStart,i-5));const vals=starts.map(s=>{const c=cycleFromStart(s,state.settings.cycleDay);return {c,spent:cycleSpent(state,c)}});const max=Math.max(state.settings.monthlySpendingTarget,...vals.map(v=>v.spent),1);return <div className="history-bars">{vals.map(v=><div key={v.c.start}><div className="bar-wrap"><span className="target-line" style={{bottom:`${state.settings.monthlySpendingTarget/max*100}%`}}/><i style={{height:`${v.spent/max*100}%`}} className={v.spent>state.settings.monthlySpendingTarget?'over':''}/></div><b>{money(v.spent)}</b><small>{v.c.label.split(' ')[0]}</small></div>)}</div>}
function WealthChart({state}){const pts=[...state.snapshots].sort((a,b)=>a.date.localeCompare(b.date)).slice(-12);if(!pts.length)return <Empty text="No snapshots yet. Closing a cycle saves one automatically."/>;const values=pts.map(p=>p.netWorth),min=Math.min(...values),max=Math.max(...values),range=Math.max(1,max-min),coords=values.map((v,i)=>`${pts.length===1?50:i/(pts.length-1)*100},${90-(v-min)/range*70}`).join(' ');return <div className="wealth-chart"><svg viewBox="0 0 100 100" preserveAspectRatio="none"><polyline points={coords}/>{pts.map((p,i)=>{const [x,y]=coords.split(' ')[i].split(',');return <circle key={p.id} cx={x} cy={y} r="1.6"/>})}</svg><div><small>{pts[0].date}</small><b>{money(values.at(-1))}</b><small>{pts.at(-1).date}</small></div></div>}
function snapshotTrend(state){const p=[...state.snapshots].sort((a,b)=>a.date.localeCompare(b.date));if(p.length<2)return null;return {value:p.at(-1).netWorth-p.at(-2).netWorth}}

function ModalRouter({modal,close,state,dispatch,metrics,setModal}){
  if(modal.type==='expense') return <ExpenseModal close={close} state={state} dispatch={dispatch}/>
  if(modal.type==='afford') return <AffordModal close={close} state={state} metrics={metrics}/>
  if(modal.type==='budget') return <BudgetModal close={close} state={state} dispatch={dispatch}/>
  if(modal.type==='transfer') return <TransferModal close={close} state={state} dispatch={dispatch} preselectedTo={modal.toId}/>
  if(modal.type==='payCard') return <PayCardModal close={close} state={state} dispatch={dispatch} card={modal.card}/>
  if(modal.type==='payday') return <PaydayModal close={close} state={state} dispatch={dispatch} metrics={metrics} setModal={setModal}/>
  if(modal.type==='account') return <AccountModal close={close} state={state} dispatch={dispatch} account={modal.account} prefillGoalId={modal.prefillGoalId}/>
  if(modal.type==='card') return <CardModal close={close} dispatch={dispatch} card={modal.card}/>
  if(modal.type==='goal') return <GoalModal close={close} dispatch={dispatch} goal={modal.goal}/>
  if(modal.type==='settings') return <SettingsModal close={close} state={state} dispatch={dispatch}/>
  if(modal.type==='closeCycle') return <CloseCycleModal close={close} state={state} dispatch={dispatch} metrics={metrics}/>
  if(modal.type==='importResult') return <Sheet title="Import complete" close={close}><div className="modal-copy"><CheckCircle2/><div><b>{modal.count} transactions imported</b><p>Historical imports count toward spending, but do not alter today's account balances. Review uncategorized items in Spending.</p></div></div><button className="full-button" onClick={close}>Done</button></Sheet>
  return null
}
function Sheet({title,close,children}){return <div className="sheet-backdrop" onMouseDown={e=>e.target===e.currentTarget&&close()}><section className="sheet"><header><h3>{title}</h3><button className="icon-button" onClick={close}><X/></button></header>{children}</section></div>}

function ExpenseModal({close,state,dispatch}){const [amount,setAmount]=useState(''),[categoryId,setCategoryId]=useState(categoryIdByName(state.categories,'Groceries')),[note,setNote]=useState(''),[method,setMethod]=useState(`account:${operatingAccount(state)?.id||''}`),[date,setDate]=useState(todayYmd());const submit=e=>{e.preventDefault();const [kind,id]=method.split(':');dispatch({type:'ADD_EXPENSE',amount:+amount,categoryId,note,date,accountId:kind==='account'?id:null,cardId:kind==='card'?id:null});close()};return <Sheet title="Add expense" close={close}><form className="form" onSubmit={submit}><label>Amount<input autoFocus type="number" min="0" step=".01" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="0 EGP" required/></label><label>Category<select value={categoryId} onChange={e=>setCategoryId(e.target.value)}>{state.categories.filter(c=>c.name!=='Needs review').map(c=><option key={c.id} value={c.id}>{c.name} · {money(c.budget)}</option>)}</select></label><label>Paid with<select value={method} onChange={e=>setMethod(e.target.value)}>{state.accounts.filter(a=>a.liquid).map(a=><option key={a.id} value={`account:${a.id}`}>{a.name} · {money(accountValue(a))}</option>)}{state.cards.map(c=><option key={c.id} value={`card:${c.id}`}>{c.name} · {money(c.balance)} due</option>)}</select></label><label>Date<input type="date" value={date} onChange={e=>setDate(e.target.value)}/></label><label>Note<input value={note} onChange={e=>setNote(e.target.value)} placeholder="Metro, Talabat, Uber..."/></label><button className="full-button">Add expense</button></form></Sheet>}

function AffordModal({close,state,metrics}){const [amount,setAmount]=useState(''),[categoryId,setCategoryId]=useState(categoryIdByName(state.categories,'Other shopping'));const amountN=+amount||0, category=state.categories.find(c=>c.id===categoryId), used=metrics.categoryMap[categoryId]||0, catLeft=(+category?.budget||0)-used, monthlyLeft=state.settings.monthlySpendingTarget-metrics.health.spent, liquidAfter=metrics.health.liquid-amountN, reserveSafe=liquidAfter>=state.settings.liquidReserve, categorySafe=amountN<=catLeft&&catLeft>=0, monthSafe=amountN<=monthlyLeft;let status='neutral',title='Enter a purchase amount',detail='FinOS will check the exact bucket, monthly target and cash floor.';if(amountN>0){if(category?.budget<=0){status='bad';title='No budget is allocated here.';detail=`${category.name} has a 0 EGP allocation. Reallocate budget first so the 7.3k target stays intentional.`}else if(!categorySafe){status='bad';title='This does not fit this category.';detail=`Only ${money(Math.max(0,catLeft))} remains in ${category.name}. You need ${money(Math.max(0,amountN-catLeft))} reallocated from another category.`}else if(!monthSafe){status='bad';title='This breaks the monthly target.';detail=`Your cycle only has ${money(Math.max(0,monthlyLeft))} left. The excess would reduce ${metrics.primaryGoal?.name||'your next goal'} funding.`}else if(!reserveSafe){status='bad';title='This breaks your liquidity floor.';detail=`After the purchase you would have ${money(liquidAfter)} liquid, below your ${money(state.settings.liquidReserve)} rule.`}else{status='good';title='You can afford this.';detail=`It fits ${category.name}. ${money(catLeft-amountN)} stays in that bucket and your monthly target remains intact.`}}return <Sheet title="Can I afford it?" close={close}><div className="form"><label>Category<select value={categoryId} onChange={e=>setCategoryId(e.target.value)}>{state.categories.filter(c=>c.name!=='Needs review').map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><div className="budget-context"><span>{category?.name}</span><b>{money(used)} spent · {money(Math.max(0,catLeft))} left</b><small>{money(category?.budget||0)} allocated this cycle</small></div><label>Purchase amount<input autoFocus type="number" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="0 EGP"/></label><div className={`decision ${status}`}>{status==='good'?<CheckCircle2/>:status==='bad'?<AlertTriangle/>:<ShieldCheck/>}<div><b>{title}</b><p>{detail}</p></div></div><button className="full-button" onClick={close}>Done</button></div></Sheet>}

function BudgetModal({close,state,dispatch}){const [draft,setDraft]=useState(()=>Object.fromEntries(state.categories.map(c=>[c.id,c.budget])));const target=state.settings.monthlySpendingTarget,total=state.categories.filter(c=>c.name!=='Needs review').reduce((s,c)=>s+(+draft[c.id]||0),0),gap=target-total;const save=()=>{if(Math.abs(gap)>.01)return;Object.entries(draft).forEach(([id,budget])=>dispatch({type:'UPDATE_CATEGORY_BUDGET',id,budget}));close()};return <Sheet title="Monthly budget" close={close}><div className="budget-head"><div><small>Target</small><b>{money(target)}</b></div><div className={Math.abs(gap)<.01?'balanced':'unbalanced'}><small>{Math.abs(gap)<.01?'Balanced':gap>0?'Unallocated':'Over target'}</small><b>{money(Math.abs(gap))}</b></div></div><p className="helper">Every category is independent. To preserve your target, allocations must add up exactly to {money(target)}.</p><div className="budget-editor">{state.categories.filter(c=>c.name!=='Needs review').map(c=>{const Icon=icons[c.icon]||MoreHorizontal;return <label key={c.id}><Icon size={16}/><span>{c.name}<small>{c.kind==='fixed'?'Committed':'Flexible'}</small></span><input type="number" min="0" value={draft[c.id]} onChange={e=>setDraft(d=>({...d,[c.id]:e.target.value}))}/></label>})}</div><button className="full-button" disabled={Math.abs(gap)>.01} onClick={save}>{Math.abs(gap)<.01?'Save balanced budget':'Balance allocations first'}</button></Sheet>}

function TransferModal({close,state,dispatch,preselectedTo}){const fromDefault=operatingAccount(state)?.id||state.accounts[0]?.id,[from,setFrom]=useState(fromDefault),[to,setTo]=useState(preselectedTo||state.accounts.find(a=>a.id!==fromDefault)?.id||''),[amount,setAmount]=useState(''),[note,setNote]=useState('');const fromAcc=state.accounts.find(a=>a.id===from);const submit=e=>{e.preventDefault();dispatch({type:'TRANSFER',fromAccountId:from,toAccountId:to,amount:+amount,note});close()};return <Sheet title="Move money" close={close}><form className="form" onSubmit={submit}><label>From<select value={from} onChange={e=>setFrom(e.target.value)}>{state.accounts.filter(a=>a.type!=='physical_gold').map(a=><option key={a.id} value={a.id}>{a.name} · {money(accountValue(a))}</option>)}</select></label><label>To<select value={to} onChange={e=>setTo(e.target.value)}>{state.accounts.filter(a=>a.id!==from&&a.type!=='physical_gold').map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>Amount<input autoFocus type="number" min="0" max={accountValue(fromAcc)} value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>Note<input value={note} onChange={e=>setNote(e.target.value)} placeholder="Renovation contribution, retirement..."/></label><div className="modal-copy"><ArrowRightLeft/><div><b>Transfers do not count as spending.</b><p>They change both account balances immediately, so goals and net worth stay consistent.</p></div></div><button className="full-button">Move money</button></form></Sheet>}

function PayCardModal({close,state,dispatch,card}){const selected=card||state.cards[0],operating=operatingAccount(state),[from,setFrom]=useState(operating?.id||''),[amount,setAmount]=useState(selected?.balance||0);if(!selected)return null;return <Sheet title="Pay credit card" close={close}><form className="form" onSubmit={e=>{e.preventDefault();dispatch({type:'PAY_CARD',cardId:selected.id,fromAccountId:from,amount:+amount});close()}}><div className="credit-focus"><CreditCard/><div><small>{selected.name}</small><b>{money(selected.balance)}</b><span>Outstanding</span></div></div><label>Pay from<select value={from} onChange={e=>setFrom(e.target.value)}>{state.accounts.filter(a=>a.liquid).map(a=><option key={a.id} value={a.id}>{a.name} · {money(accountValue(a))}</option>)}</select></label><label>Amount<input type="number" value={amount} onChange={e=>setAmount(e.target.value)} max={selected.balance}/></label><button className="full-button">Pay card</button><button type="button" className="text-button" onClick={()=>{dispatch({type:'MARK_CARD_PAID',cardId:selected.id});close()}}>Already paid outside FinOS — mark only</button></form></Sheet>}

function PaydayModal({close,state,dispatch,metrics,setModal}){const retirement=metrics.retirement,goal=metrics.primaryGoal,goalAccount=state.accounts.find(a=>a.goalId===goal?.id),available=state.profile.salary-state.settings.monthlySpendingTarget-(retirement?.monthlyContribution||0);return <Sheet title="Payday plan" close={close}><div className="payday-flow"><div><span>Salary</span><b>{money(state.profile.salary)}</b></div><ArrowDown/><div><span>Keep for monthly spending</span><b>{money(state.settings.monthlySpendingTarget)}</b></div><ArrowDown/><div className="protected"><span>Retirement first</span><b>{money(retirement?.monthlyContribution||0)}</b></div><ArrowDown/><div><span>{goal?.name||'Top goal'}</span><b>{money(Math.max(0,available))}</b></div></div><p className="helper">This is a plan, not fake money movement. Use the actions below when you actually transfer funds.</p><div className="stack-actions"><button className="full-button" onClick={()=>setModal({type:'transfer',toId:retirement?.id})}>Fund retirement</button>{goalAccount&&<button className="secondary-button" onClick={()=>setModal({type:'transfer',toId:goalAccount.id})}>Fund {goal.name}</button>}</div></Sheet>}
function ArrowDown(){return <div className="flow-arrow">↓</div>}

function AccountModal({close,state,dispatch,account,prefillGoalId}){const [form,setForm]=useState(account||{id:uid(),name:'',type:'investment',balance:0,liquid:false,operating:false,goalId:prefillGoalId||null,monthlyContribution:0,annualRate:0,note:'',qty:0,unitPrice:0,karat:'24K'});const change=(k,v)=>setForm(f=>({...f,[k]:v}));return <Sheet title={account?'Edit account':'Add account / asset'} close={close}><form className="form" onSubmit={e=>{e.preventDefault();const normalized={...form,balance:+form.balance||0,qty:+form.qty||0,unitPrice:+form.unitPrice||0,monthlyContribution:+form.monthlyContribution||0,annualRate:+form.annualRate||0,liquid:form.type==='cash'?!!form.liquid:false};dispatch({type:account?'UPDATE_ACCOUNT':'ADD_ACCOUNT',account:normalized});close()}}><label>Name<input value={form.name} onChange={e=>change('name',e.target.value)} required/></label><label>Type<select value={form.type} onChange={e=>change('type',e.target.value)}><option value="cash">Cash / wallet</option><option value="investment">Investment</option><option value="gold_fund">Gold fund</option><option value="physical_gold">Physical gold</option><option value="retirement">Retirement</option></select></label>{form.type==='physical_gold'?<><label>Grams<input type="number" step=".01" value={form.qty} onChange={e=>change('qty',e.target.value)}/></label><label>Current EGP / gram<input type="number" value={form.unitPrice} onChange={e=>change('unitPrice',e.target.value)}/></label><label>Karat<input value={form.karat} onChange={e=>change('karat',e.target.value)}/></label></>:<label>Current balance<input type="number" step=".01" value={form.balance} onChange={e=>change('balance',e.target.value)}/></label>}<label>Linked goal<select value={form.goalId||''} onChange={e=>change('goalId',e.target.value||null)}><option value="">None</option>{state.goals.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></label>{form.type==='retirement'&&<label>Monthly contribution<input type="number" value={form.monthlyContribution} onChange={e=>change('monthlyContribution',e.target.value)}/></label>}<label>Annual rate / assumption<input type="number" step=".01" value={form.annualRate} onChange={e=>change('annualRate',e.target.value)}/></label>{form.type==='cash'&&<label className="check-label"><input type="checkbox" checked={!!form.liquid} onChange={e=>change('liquid',e.target.checked)}/>Count as liquid money</label>}<label>Note<input value={form.note||''} onChange={e=>change('note',e.target.value)}/></label><button className="full-button">Save account</button></form></Sheet>}

function CardModal({close,dispatch,card}){const [form,setForm]=useState(card);return <Sheet title="Credit card" close={close}><form className="form" onSubmit={e=>{e.preventDefault();dispatch({type:'UPDATE_CARD',card:{...form,balance:+form.balance||0,dueDay:+form.dueDay||5}});close()}}><label>Card name<input value={form.name} onChange={e=>setForm(f=>({...f,name:e.target.value}))}/></label><label>Outstanding balance<input type="number" step=".01" value={form.balance} onChange={e=>setForm(f=>({...f,balance:e.target.value}))}/></label><label>Due day<input type="number" min="1" max="31" value={form.dueDay} onChange={e=>setForm(f=>({...f,dueDay:e.target.value}))}/></label><button className="full-button">Save</button></form></Sheet>}
function GoalModal({close,dispatch,goal}){const [form,setForm]=useState(goal||{id:uid(),name:'',target:0,priority:9,targetDate:'',note:''});return <Sheet title={goal?'Edit goal':'New goal'} close={close}><form className="form" onSubmit={e=>{e.preventDefault();dispatch({type:goal?'UPDATE_GOAL':'ADD_GOAL',goal:{...form,target:+form.target||0,priority:+form.priority||9}});close()}}><label>Name<input value={form.name} onChange={e=>setForm(f=>({...f,name:e.target.value}))}/></label><label>Target<input type="number" value={form.target} onChange={e=>setForm(f=>({...f,target:e.target.value}))}/></label><label>Priority<input type="number" min="1" value={form.priority} onChange={e=>setForm(f=>({...f,priority:e.target.value}))}/></label><label>Target date<input type="date" value={form.targetDate||''} onChange={e=>setForm(f=>({...f,targetDate:e.target.value}))}/></label><label>Note<input value={form.note||''} onChange={e=>setForm(f=>({...f,note:e.target.value}))}/></label><button className="full-button">Save goal</button></form></Sheet>}

function SettingsModal({close,state,dispatch}){const [profile,setProfile]=useState(state.profile),[settings,setSettings]=useState(state.settings),[fire,setFire]=useState(state.fire);return <Sheet title="FinOS settings" close={close}><form className="form" onSubmit={e=>{e.preventDefault();dispatch({type:'UPDATE_SETTINGS',profile:{...profile,salary:+profile.salary||0,age:+profile.age||0,retirementAge:+profile.retirementAge||65},settings:{...settings,liquidReserve:+settings.liquidReserve||0,monthlySpendingTarget:+settings.monthlySpendingTarget||0},fire:{...fire,monthlyLifestyle:+fire.monthlyLifestyle||0,withdrawalRate:+fire.withdrawalRate||0,realReturn:+fire.realReturn||0}});close()}}><label>Net monthly salary<input type="number" value={profile.salary} onChange={e=>setProfile(p=>({...p,salary:e.target.value}))}/></label><label>Monthly spending target<input type="number" value={settings.monthlySpendingTarget} onChange={e=>setSettings(s=>({...s,monthlySpendingTarget:e.target.value}))}/></label><label>Liquid reserve floor<input type="number" value={settings.liquidReserve} onChange={e=>setSettings(s=>({...s,liquidReserve:e.target.value}))}/></label><label>Age<input type="number" value={profile.age} onChange={e=>setProfile(p=>({...p,age:e.target.value}))}/></label><label>Retirement safety age<input type="number" value={profile.retirementAge} onChange={e=>setProfile(p=>({...p,retirementAge:e.target.value}))}/></label><label>Retirement lifestyle / month<input type="number" value={fire.monthlyLifestyle} onChange={e=>setFire(f=>({...f,monthlyLifestyle:e.target.value}))}/></label><label>Withdrawal rate %<input type="number" step=".1" value={fire.withdrawalRate} onChange={e=>setFire(f=>({...f,withdrawalRate:e.target.value}))}/></label><label>Real return assumption %<input type="number" step=".1" value={fire.realReturn} onChange={e=>setFire(f=>({...f,realReturn:e.target.value}))}/></label><div className="modal-copy"><ShieldCheck/><div><b>Financial month stays 28th → 27th.</b><p>FinOS uses one canonical model; settings here update every dependent screen.</p></div></div><button className="full-button">Save settings</button></form></Sheet>}

function CloseCycleModal({close,state,dispatch,metrics}){const cycle=metrics.cycle,spent=cycleSpent(state,cycle),under=state.settings.monthlySpendingTarget-spent,reviewCount=cycleExpenses(state,cycle).filter(t=>state.categories.find(c=>c.id===t.categoryId)?.name==='Needs review').length;const closure={id:uid(),cycleStart:cycle.start,cycleEnd:cycle.end,label:cycle.label,spent,target:state.settings.monthlySpendingTarget,variance:under,netWorth:netWorth(state),cardPaid:metrics.health.cardPaid,retirementFunded:metrics.health.retirementFunded,reviewCount,closedAt:todayYmd()};return <Sheet title={`Close ${cycle.label}`} close={close}><div className="close-summary"><div><span>Spending</span><b>{money(spent)} / {money(state.settings.monthlySpendingTarget)}</b></div><div><span>Budget result</span><b className={under>=0?'positive':'negative'}>{under>=0?money(under)+' under':money(Math.abs(under))+' over'}</b></div><div><span>Credit card</span><b>{metrics.health.cardPaid?'✓ Paid':'Needs attention'}</b></div><div><span>Retirement</span><b>{metrics.health.retirementFunded?'✓ Funded':'Not recorded'}</b></div><div><span>Net worth</span><b>{money(netWorth(state))}</b></div><div><span>Needs review</span><b>{reviewCount}</b></div></div>{(!metrics.health.cardPaid||!metrics.health.retirementFunded||reviewCount>0)&&<div className="decision bad"><AlertTriangle/><div><b>You can still close it.</b><p>FinOS will preserve these exceptions in the permanent cycle report so they do not disappear.</p></div></div>}<button className="full-button" onClick={()=>{dispatch({type:'CLOSE_CYCLE',closure});close()}}>Close cycle & save snapshot</button></Sheet>}

function parseCsvLine(line){const out=[];let cur='',quoted=false;for(let i=0;i<line.length;i++){const ch=line[i];if(ch==='"'){if(quoted&&line[i+1]==='"'){cur+='"';i++}else quoted=!quoted}else if(ch===','&&!quoted){out.push(cur.trim());cur=''}else cur+=ch}out.push(cur.trim());return out}
function parseDateLoose(v){if(!v)return null;const s=v.trim();let m=s.match(/(\d{1,2})[\/-](\d{1,2})[\/-](\d{2,4})/);if(m){let [,d,mo,y]=m;if(y.length===2)y='20'+y;return `${y}-${String(mo).padStart(2,'0')}-${String(d).padStart(2,'0')}`}m=s.match(/(\d{4})[\/-](\d{1,2})[\/-](\d{1,2})/);if(m)return `${m[1]}-${String(m[2]).padStart(2,'0')}-${String(m[3]).padStart(2,'0')}`;return null}
function guessCategory(state,text){const s=text.toLowerCase(),name=s.includes('chillout')?'Fuel':s.includes('muscle temple')?'Gym sinking fund':s.includes('max muscle')?'Supplements':s.includes('talabat')?'Food delivery / Talabat':s.includes('uber')?'Uber / ride-hailing':s.includes('amazon')&&s.includes('prime')?'Amazon Prime':s.includes('metro')||s.includes('market')||s.includes('carrefour')?'Groceries':s.includes('telda')?'Needs review':'Needs review';return categoryIdByName(state.categories,name)}
async function handleCsv(e,state,dispatch,setModal){const file=e.target.files?.[0];if(!file)return;const text=await file.text(),lines=text.split(/\r?\n/).filter(Boolean),rows=lines.map(parseCsvLine);const imported=[];for(let i=1;i<rows.length;i++){const row=rows[i],date=row.map(parseDateLoose).find(Boolean);if(!date)continue;const numeric=row.map(v=>Number(String(v).replace(/[ ,EGP]/gi,''))).filter(n=>Number.isFinite(n));if(!numeric.length)continue;let amount=Math.abs(numeric.at(-1));if(!amount)continue;const joined=row.join(' ');if(/thndr/i.test(joined))continue;imported.push({id:uid(),date,kind:'expense',amount,categoryId:guessCategory(state,joined),note:joined.slice(0,120),merchant:joined.slice(0,80),accountId:null,cardId:null,affectsBalance:false,source:'csv'})}dispatch({type:'IMPORT_TRANSACTIONS',transactions:imported});setModal({type:'importResult',count:imported.length});e.target.value=''}

createRoot(document.getElementById('root')).render(<App/>)
